### ISSUE TITLE
Attribute Definitions do not include asynchronous functions

### ISSUE THREAD

**Issue by gkemp94** [dynamoose/dynamoose#1012]
Hi, 
New user to dynamoose, and happy to help by opening a PR with a few fixes for typescript definitions. One thing I noticed was that the validation, set and get functions are not typed with async functions. 
 
https://github.com/dynamoose/dynamoose/blob/2c4dc668f91108a412a51fd39b5ff3f1ed367e39/lib/Schema.ts#L255

This causes a typescript error below:
`TS2322: Type '(value: ValueType) => Promise<ValueType>' is not assignable to type '(value: ValueType) => ValueType'.
  Type 'Promise<ValueType>' is not assignable to type 'ValueType'.
    Type 'Promise<ValueType>' is not assignable to type '{ [key: string]: ValueType; }'.
      Index signature is missing in type 'Promise<ValueType>'.`

If you're happy enough allowing me to submit a PR, I'll gladly start one and get it submitted. 
Thank

**Comment by fishcharlie** [comment]
@gkemp94 Verify that this there isn't a PR open for this already, then yes. Please next time also follow the issue template. Closing due to not following issue template, but will accept PR for this.
