### ISSUE TITLE
[BUG] replace rm command using cross-platform rimraf

### ISSUE THREAD

**Issue by noamanilyas** [dynamoose/dynamoose#1067]
### Summary:
rm -rf  is not compatible on windows change it to rimraf for cross-platform compatiblity.

### Current implementation: 
package.json
`"build:clean": "rm -rf dist",`

#### New implementation

`"build:clean": "rimraf dist",`

Operating System:
Windows 10

**Comment by fishcharlie** [comment]
@noamanilyas Ideally, I'd like to avoid adding another dependency to Dynamoose.

Just out of curiosity, why are you running into this? `build:clean` should only be run for internal development purposes. Like can you give more information here about why you are needing to run this script? Just using Dynamoose shouldn't require this script to be run.
