### ISSUE TITLE
[FEATURE] Call set on search fields in query/get/delete/scan/update

### ISSUE THREAD

**Issue by MaximilianSchon** [dynamoose/dynamoose#1093]
### Summary:
I am using a single table structure, which means most of the the primary keys in my table have some kind of indicator of what type they are, so that it is possible to query them. An example from AWS Re:invent can be seen here: https://www.youtube.com/watch?v=DIQVJqiSUkE&t=2128s. 

This does however not mix very well with how dynamoose searches for items, as the set is not called before fetch. It seems like the same problem arises with update, probably because of the same reason. That leaves me with a lot of queries looking like the example under general. 

#### Schema
```
export const SurveySchema = new dynamoose.Schema({
    "PK": {
        "type": String,
        "default": () => crypto
            .randomBytes(16)
            .toString("hex"),
        "get": (value : string) => value.replace("Survey#", ""),
        "set": (value : string) => `Survey#${value}`,
        "hashKey": true
    },
    "SK": {
        "type": String,
        "rangeKey": true,
    }
}
```
#### Model
```
export const SurveyModel  = dynamoose.model("Survey", SurveySchema, 
    {
        create: false,
        update: false, 
        waitForActive: {
            enabled: false,
            check: null
        },
        suffix: "-" + process.env.ENV,
    })
```
#### General
```
    delete(PK: string, SK: string): Promise<void> {
        return Survey.delete({PK: `Survey#${PK}`, SK: SK});
    }
```

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@MaximilianSchon Adding this to the v3 planning (#1040). One thing I'm planning on working on is having a Model represent a type of data as opposed to a DynamoDB table. Which should also help this as well. But ensuring `get` and `set` get called on all methods is important as well.
