### ISSUE TITLE
[FEATURE] Timestamps should be customizable to use JSON date instead of epoch

### ISSUE THREAD

**Issue by henhal** [dynamoose/dynamoose#1164]
### Summary:

The automatic timestamps is a nice feature, but it would be nice if you could use another format such as JSON dates.

Suggestion for an extension to the options to allow for custom formatting:

```
{
  timestamps: {
    createdAt: 'createdTime',
    updatedAt: 'modifiedTime',
    format: ms => new Date(ms).toJSON()
  },
}
``` 

For even simpler configuration, the type of `format` could be e.g. `"ms" | "json" | (ms: number) => any`, so that you could use `format: 'json'`

#### Schema
```
// Code here
```

#### Model
```
// Code here
```

#### General
```
// Code here
```

### Environment:

Operating System: Ubuntu
Operating System Version: 18.04
Node.js version (`node -v`): 14.2.0
NPM version: (`npm -v`): 6.14.4
Dynamoose version: 2.7.3

### Other:
- [ ] I have read through the Dynamoose documentation before posting this issue
- [ ] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [ ] I have filled out all fields above
- [ ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@henhal What would a JSON formatted Date look like?

**Comment by henhal** [comment]
@fishcharlie Well, I used the term "JSON date" loosely, as strictly speaking JSON does not define date formats. I'm referring to a RFC3339 date such as `2021-03-26T12:00:27Z` as per https://tools.ietf.org/html/rfc3339#page-8, or what you get in JavaScript from `new Date().toJSON()`.

**Comment by fishcharlie** [comment]
@henhal I thought about this, but I realized that it doesn't make a lot of sense.

- `2021-03-26T12:00:27Z` (your string) is 20 characters
- `1616760027` (epoch timestamp) is 10 characters
- `1616760027000` (epoch timestamp for milliseconds) is 13 characters

Dynamoose returns a Date object back to you, which you can use to easily run `.toJSON()` on to get your string.

What is the purpose/use case behind storing an extra 7-10 characters in your DynamoDB table that will produce the same result? Doesn't seem very efficient.

Not saying I'm completely opposed, but just trying to understand the use case so I can implement it in a good way or if it should even be implemented at all.

**Comment by henhal** [comment]
@fishcharlie It doesn't make a lot of sense? Really? ISO8601 / RFC3339 dates are extremely common in all kinds of stored structures. It combines human readability with the ability to compare dates just like epoch timestamps.

[AWS' own DynamoDB data type guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes
) mentions dates both under number data types and string data types:

>You can use the string data type to represent a date or a timestamp. One way to do this is by using ISO 8601 strings, as shown in these examples:
>
> 2016-02-15
>
>2015-12-21T17:42:34Z
>
>20150311T122706Z
>
> For more information, see http://en.wikipedia.org/wiki/ISO_8601.

And, while I used to work as an embedded C programmer for years, struggling to save every byte of memory, that is hardly a concern with a cloud database like DynamoDB, so the argument that a ISO8601 date consumes 20 characters compared to 10-13 characters for a number (or even less, I'm not sure normal non-bigints are stored as strings internally) seems like a suboptimization. Most projects I've worked with has used ISO8601 dates for most things due to human readable data being easier to debug while exploring data in the DynamoDB explorer etc.

Anyway, this feature was not about forcing anyone to use one format or the other, it was a suggestion for a nice customization option to accomodate for a very common use-case. You may close it if you like, I decided dynamoose wasn't for me anyway so I don't have a strong personal interest in it anymore. :man_shrugging:

**Comment by fishcharlie** [comment]
@henhal Totally fair. Appreciate the discussion. Just to be clear and make sure I understand, this is primarily for viewing the data in the DynamoDB Console or other 3rd party tools, correct? Because within your application you can easily do `toJSON` as you mentioned. So that is why I was misunderstanding the use case here. It's specifically related to viewing the raw data?

**Comment by henhal** [comment]
I'd say there could be any reason for choosing ISO 8601 dates when modeling your data, simplified data exploration is just one that came to mind. I've spent countless hours debugging customer issuers related to things triggered at a specific date, and having to deal with epoch times certainly wouldn't have made it easier. 😁
My point is mostly that it's a common industry practice, and it might be nice to allow it as an option. No big deal. 
Cheers.

**Comment by aatargetable** [comment]
Could we re-open this? I completely agree we should have the ability to determine the formatting of Date types. Having ISO 8601 dates is definitely an industry standard and the way to go if you don't want to drive yourself mad trying to debug issues via the AWS console.

**Comment by khanghua1505** [comment]
I have the same issue. I use AWS amplify to generate the  data models. In my bussiness logic, I must create the custom mutations or queries, I use lambda as datasources. The amplify use ISO string for AWSDateTime. 
In my solution, Insteads Date, I use String and convert String to Date. I hope the dynamoose can be custom the timestamps.

**Comment by bruno-johann** [comment]
I'm having the same problem, it would be really nice if we could change the date format

**Comment by fishcharlie** [comment]
#1498 is a PR that adds support for ISO-8601 Dates. That PR does not include support for using ISO-8601 Dates for timestamps. I'm about to start work on adding support for ISO-8601 Dates for timestamps.
