### ISSUE TITLE
[DOCUMENTATION REQUEST] dynamic keys in Object type

### ISSUE THREAD

**Issue by braco** [dynamoose/dynamoose#1173]
I looked through all the documentation and issues, and can't figure out how to cover this basic use case that has an object with dynamic key names:

```
{
    name: "...",
    entries: {
      [dynamic key name]: Date,
      [dynamic key name]: Date,
      [dynamic key name]: Date,
      [dynamic key name]: Date
    }
}
```

This format would be used to add {[id]: date} properties to `entries`.

Apologies if I missed something.

**Comment by fishcharlie** [comment]
@braco There is no way to guarantee that all `entries` properties are of type Date. However if you are ok with that limitation, look into the [`saveUnknown`](https://dynamoosejs.com/guide/Schema#new-dynamooseschemaschema-options) schema option.

**Comment by braco** [comment]
Got it, thanks @fishcharlie. Is there any way to set default values in new entries, or is this the only thing I can do?:

```
const schema = new dynamoose.Schema({
  name: {
    type: String,
    hashKey: true
  },
  entries: Object
});
```

A section with recipes for common scenarios in the docs would be helpful, I pieced most of the usage together from starter projects.

**Comment by fishcharlie** [comment]
@braco Default entries for your dynamic key names? No. Not possible currently. So yes, your example code you gave is all you can do (related to your question) + adding that `saveUnknown` option.

Our documentation has a **lot** of examples and sample code in it. Is there something you feel like it's missing? It's difficult to give examples of everything Dynamoose can't do. But almost every puzzle piece is clearly described in the documentation. So it should be pretty straight forward to piece together.

If you feel like something is missing tho, please let me know.

**Comment by braco** [comment]
Feel like there's a lot of snippets but it's not immediately clear on how everything fits together – it's usually easier to jump into things via working, best practice code. It would be helpful to have self-contained, end to end examples. My situation above could be one scenario ("Nested object with dynamic key names"), and the code would be schema definition and updating `entries` in place (which I'm not sure how to do still).

"Here's a schema covering X scenario, here's how to define that and update the data"

This could be an `examples` folder in a repo.

I realize this is all subjective, I appreciate the consideration and openness to hearing feedback!
