### ISSUE TITLE
What does it mean to have queriedCount to be undefined?

### ISSUE THREAD

**Issue by awesomelike** [dynamoose/dynamoose#1234]
### Discussed in https://github.com/dynamoose/dynamoose/discussions/1233

<div type='discussions-op-text'>

<sup>Originally posted by **awesomelike** August 12, 2021</sup>
I am using Query operation as the following:
`Model.query('gsi_hash_key').eq('some_id').using('gsi_name').all();`

After executing it, in the result array, I am getting 1 document and `queriedCount: undefined`. 
I could not find any information on the docs about what it means?

Can anyone help?

</div>

**Comment by fishcharlie** [comment]
Sounds like a bug. Please submit an actual issue with an MCVE, and all the requested details.
