### ISSUE TITLE
[TASK] Add Node.js v16.x to CI test suite

### ISSUE THREAD

**Issue by fishcharlie** [dynamoose/dynamoose#1262]
### Summary:

Add Node.js v16.x to CI test suite

**Comment by vishal-codes** [comment]
> ### Summary:
> 
> Add Node.js v16.x to CI test suite

I want to work on this, Can you help me with getting started?

**Comment by fishcharlie** [comment]
@vishal-codes 

- Read the [CONTRIBUTING.md](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md) document.
- Then it'll likely be as simple as adding the version to the `node-version` array in the https://github.com/dynamoose/dynamoose/blob/master/.github/workflows/ci.yml file and submitting a PR.

**Comment by vishal-codes** [comment]
> @vishal-codes
> 
>     * Read the [CONTRIBUTING.md](https://github.com/dynamoose/dynamoose/blob/master/CONTRIBUTING.md) document.
> 
>     * Then it'll likely be as simple as adding the version to the `node-version` array in the https://github.com/dynamoose/dynamoose/blob/master/.github/workflows/ci.yml file and submitting a PR.

Okay got it, thank you !

**Comment by vishal-codes** [comment]
Hey @fishcharlie I have opened a <a href="https://github.com/dynamoose/dynamoose/pull/1276">PR</a> which will get this task done. Can you please review it?
