### ISSUE TITLE
[BUG] - ability to add GSI SK

### ISSUE THREAD

**Issue by Seamus1989** [dynamoose/dynamoose#1345]
### Summary:

I am creating a schema referred to in the Dynamo docs, as GSI overloading.

See https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-modeling-nosql-B.html
And https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-gsi-overloading.html

Essentially you create a hash and range key on the base table, and then create a GSI. The partition key of the GSI is the sort key of the base table, and the GSI sort key is a new key.

The problem is, I've been trying to write this schema using dynamoose but I cant see how its possible. I've briefly dived into the sort code and I think the issue is that the `getRangeKey` function inside `Schema.js` always defaults to the `rangeKey` key of the base table when getting the range key for the secondary global indexes. I'm not sure I currently have the time to verify this as the issue and fix but I'm just bringing it to the attention for all.

A quick glance solution might be to defined a new function `getGsiRangeKey` for use when creating a composite key on a GSI. Unsure if anyone else has had a similar issue, but this seems like quite a popular choice for modelling Dynamo indexes and keys, so I'm quite confused how this library doesn't seem to currently support this. Maybe I'm being unnecessarily critical, so if that is the case, I apologise - I'm new(ish) to dynamo and indeed this library.

#### Schema

This is a basic structure, of how I would imagine the Dynamoose schema to look, I will also provide the console.logged results when deploying this via AWS-CDK.
```
const keyIndexValues = {
  partitionKey: 'pk',
  sortKey: 'sk',
  globalSecondaryIndex: 'gsi',
  globalSecondaryIndexPartitionKey: 'gsi1pk',
  globalSecondaryIndexSortKey: 'gsi1sk',
};

const schemaIndexesAndKeys = {
  [keyIndexValues.partitionKey]: {
    type: String,
    hashKey: true,
    required: true,
  },
  [keyIndexValues.globalSecondaryIndexSortKey]: String,
  [keyIndexValues.sortKey]: {
    type: String,
    rangeKey: true,
    required: true,
  },
  [keyIndexValues.globalSecondaryIndexPartitionKey]: {
    type: String,
    required: true,
    index: {
      // create a secondary global index with primary key given by the sort key of the base table
      name: keyIndexValues.globalSecondaryIndex,
      rangeKey: keyIndexValues.globalSecondaryIndexSortKey,
      global: true,
    },
  },
};

```
During deployments, this has the output given

```
{
  indexName: 'gsi',
  partitionKey: { name: 'gsi1pk', type: 'S' },
  sortKey: { name: 'sk', type: 'S' }
}
```

Whereas we want...

```
{
  indexName: 'gsi',
  partitionKey: { name: 'gsi1pk', type: 'S' },
  sortKey: { name: 'gsi1sk', type: 'S' }
}
```
I hope this makes sense, and if you need any further information I can provide it. Thanks.

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [ ] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@Seamus1989 Can't reproduce this when running Dynamoose v2.8.5.

For your table you have `pk` as the hashKey and `sk` as the rangeKey. Then you have 1 GSI with the hashKey as `gsi1pk` and the rangeKey as `gsi1sk`.

This is not an enhancement or feature request as far as I can tell since the [`index` documentation](https://dynamoosejs.com/guide/Schema#index-boolean--object--array) includes information for `rangeKey`.

You mention `I will also provide the console.logged results`, but don't really go into detail about how you generated that. What exactly did you `console.log`? How did you end up with that output? As stated in the [Contributing document](https://github.com/dynamoose/dynamoose/blob/main/CONTRIBUTING.md#minimal-complete-and-verifiable-example-mcve) it's really helpful if you can provide an MCVE. Although you provided a few components of that, it's not a complete example.

Finally, you mention `AWS-CDK`. I actually haven't used AWS-SDK before. But possibly something there is messing up? Have you isolated this issue to Dynamoose specifically? 

You can see the exact code I ran along with the output when running it below. Everything looks fine to me. The request being sent to AWS is exactly what I'd expect.

```js
const keyIndexValues = {
	partitionKey: 'pk',
	sortKey: 'sk',
	globalSecondaryIndex: 'gsi',
	globalSecondaryIndexPartitionKey: 'gsi1pk',
	globalSecondaryIndexSortKey: 'gsi1sk',
};

const schemaIndexesAndKeys = {
	[keyIndexValues.partitionKey]: {
		type: String,
		hashKey: true,
		required: true,
	},
	[keyIndexValues.globalSecondaryIndexSortKey]: String,
	[keyIndexValues.sortKey]: {
		type: String,
		rangeKey: true,
		required: true,
	},
	[keyIndexValues.globalSecondaryIndexPartitionKey]: {
		type: String,
		required: true,
		index: {
			// create a secondary global index with primary key given by the sort key of the base table
			name: keyIndexValues.globalSecondaryIndex,
			rangeKey: keyIndexValues.globalSecondaryIndexSortKey,
			global: true,
		},
	},
};

const dynamoose = require('dynamoose');

const schema = new dynamoose.Schema(schemaIndexesAndKeys);
const model = dynamoose.model('test', schema, {
	"create": false,
	"update": false,
	"waitForActive": false
});
(async () => {
	console.log(JSON.stringify(await model.table.create.request(), null, "\t"));
})();
```

```
node index.js
{
	"TableName": "test",
	"ProvisionedThroughput": {
		"ReadCapacityUnits": 1,
		"WriteCapacityUnits": 1
	},
	"AttributeDefinitions": [
		{
			"AttributeName": "pk",
			"AttributeType": "S"
		},
		{
			"AttributeName": "sk",
			"AttributeType": "S"
		},
		{
			"AttributeName": "gsi1pk",
			"AttributeType": "S"
		},
		{
			"AttributeName": "gsi1sk",
			"AttributeType": "S"
		}
	],
	"KeySchema": [
		{
			"AttributeName": "pk",
			"KeyType": "HASH"
		},
		{
			"AttributeName": "sk",
			"KeyType": "RANGE"
		}
	],
	"GlobalSecondaryIndexes": [
		{
			"IndexName": "gsi",
			"KeySchema": [
				{
					"AttributeName": "gsi1pk",
					"KeyType": "HASH"
				},
				{
					"AttributeName": "gsi1sk",
					"KeyType": "RANGE"
				}
			],
			"Projection": {
				"ProjectionType": "ALL"
			},
			"ProvisionedThroughput": {
				"ReadCapacityUnits": 1,
				"WriteCapacityUnits": 1
			}
		}
	]
}
```

**Comment by Seamus1989** [comment]
hey thanks for the reply. My apologies, further investigation and I found an error with another lib - sorry its been one of them days. Thanks for the reply, and have fun. Closing.

**Comment by fishcharlie** [comment]
@Seamus1989 Awesome! Glad to hear you found the cause. Feel free to submit a new issue if you ever run into more problems or have suggestions for Dynamoose.
