### ISSUE TITLE
[FEATURE] Remove promises from Schema.getIndex...() functions

### ISSUE THREAD

**Issue by mendellerner** [dynamoose/dynamoose#1356]
### Summary:
All `Schema.getIndex...()` functions return a promise which is unnecessary and prohibits these functions being used outside async operations.

#### Schema
```TypeScript
// Schema.d.ts
getIndexAttributes: () => Promise<{
    index: IndexDefinition;
    attribute: string;
}[]>;
```

### Environment:

Operating System: MacOS
Operating System Version: Monterey 12.2
Node.js version (node -v): v14.17.5
NPM version: (npm -v): 6.14.14
Dynamoose version: 2.8.5

### Other information (if applicable):
N/A

### Other:

I have read through the Dynamoose documentation before posting this issue
I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
I have filled out all fields above
I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@mendellerner PR is up for this at #1357.

**However** this is not supported behavior, therefore I did not add any unit tests for this. The `Schema.getIndex_____` methods are all considered internal & undocumented methods. This means the behavior can change at anytime **without** as SEMVER breaking change version. You can read more at our FAQ page: https://dynamoosejs.com/other/FAQ#can-i-use-an-undocumented-property-class-method-or-function-in-dynamoose.

I highly encourage you to avoid using these internal methods to Dynamoose and stick to the fully documented API that Dynamoose exposes to you.

---

It sounds like you are wanting to use `getIndexAttributes`. In #1040 I mention the following:

> I use getIndexAttributes in another project, which is really bad practice and doesn't follow the Dynamoose guidelines, we should expose that

So I do plan on exposing this specific method and making it public and fully documented (with test coverage) in v3 (hopefully).

If there are other internal methods or properties you would like to use please create specific feature request issues for those things.

**Comment by fishcharlie** [comment]
Related: #1362

**Comment by mendellerner** [comment]
Thanks!
