### ISSUE TITLE
[BUG] Model.delete does not throw when trying to delete an item that does not exist

### ISSUE THREAD

**Issue by etienne-07** [dynamoose/dynamoose#1407]
Hi,
The Model.delete works well in a way that it successfully deletes an existing item. However when trying to delete an item that does not exist in dynamoDB, it will not throw any error.
Is this a known issue?
I am using dynamoose version 2.8.5.
I have replicated the documentation code example. In any situation the error callback will be undefined and the console.log "Successfully deleted item" will be printed.

```
User.delete({"id": userId}, (error) => {
    if (error) {
        console.error(error);
    } else {
        console.log("Successfully deleted item");
    }
});
```

Thanks a lot for your help.

**Comment by fishcharlie** [comment]
Why would you want to throw an error if the item doesn't exist? That is so counter intuitive. The end result in your database is exactly what you are asking for, the object doesn't exist. There is no error there. You asked for the object to not exist in your database, it doesn't exist in the database, therefore the operation was successful.
