### ISSUE TITLE
[BUG] type is mis-defined for ItemSaveSettings

### ISSUE THREAD

**Issue by lastmirage** [dynamoose/dynamoose#1423]
ItemSaveSettings defined at [here](https://github.com/dynamoose/dynamoose/blob/8d8d5fe6dedeb8480fa02f422469754a8895f666/packages/dynamoose/lib/Item.ts#L23)

in this define, return's type is "request" | "Item"

but in save function in [here](https://github.com/dynamoose/dynamoose/blob/8d8d5fe6dedeb8480fa02f422469754a8895f666/packages/dynamoose/lib/Item.ts#L384), it defined like {return: "item"}

so which is corret ? item or Item ?

**Comment by andrewda** [comment]
Good catch, `item` is indeed correct. https://github.com/dynamoose/dynamoose/pull/1424 should fix it.
