### ISSUE TITLE
[FEATURE] Publish already implemented features

### ISSUE THREAD

**Issue by danieldspx** [dynamoose/dynamoose#1564]
### Summary:

Hey, I've noticed that the last release was 4 months ago, but there was some neat features added. The one I am looking for is to set the tableName as the model property. This was already implemented in https://github.com/dynamoose/dynamoose/pull/1522 and docs wwere updated at https://github.com/dynamoose/dynamoose/pull/1515 but I see that the lastest version does not include those changes. Could you please update a new version? Thanks for the amazing lib.

**Comment by danieldspx** [comment]
@fishcharlie Can you do that please?

**Comment by fishcharlie** [comment]
This will be done today or tomorrow! Sorry for the delay.
