### ISSUE TITLE
[FEATURE] Improve configuration documentation

### ISSUE THREAD

**Issue by williamrjribeiro** [dynamoose/dynamoose#1565]
### Summary:
The [Dynamoose Specific Configuration](https://dynamoosejs.com/getting_started/Configure#dynamoose-specific) doc page shows a way of configuring the internal DynamoDB Client that is not shown on [AWS SDK Docs](https://github.com/aws/aws-sdk-js-v3/blob/main/packages/credential-providers/README.md).

My suggestion is to add another example showing different ways of setting the credentials or adding the external link to the AWS SDK docs.

### Code sample:
Not applicable

### Environment:
N/A
Operating System: N/A
Operating System Version: N/A
Node.js version (`node -v`): N/A
NPM version: (`npm -v`): N/A
Dynamoose version: N/A

### Other information (if applicable):
I couldn't find any docs from AWS showing examples of setting DynamoDB Client credentials the way it's documented in Dynamoose, not even for `v2` of the AWS JS SDK.

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
This was fixed in #1506. It will be deployed to the website in the next version of Dynamoose.

Sadly, AWS's documentation for AWS SDK JS v3 is absolutely awful. So there is no direct documentation for this that I can find. But if you look at the typings #1506 is a valid way to setup the credentials.
