### ISSUE TITLE
[BUG] `deep_copy` fix is not released in 4.0.1

### ISSUE THREAD

**Issue by b4rtaz** [dynamoose/dynamoose#1699]
### Summary:

This fix https://github.com/dynamoose/dynamoose/pull/1673 seems to be not released in the latest version (4.0.1) of Dynamoose.

<img width="829" alt="image" src="https://github.com/user-attachments/assets/6ac710d3-8c04-4ddd-8f09-79686e95ba04">

* The new version does not use the `js-object-utilities` dependency.
* The code in the package still use the `js-object-utilities` dependency.

**Comment by fishcharlie** [comment]
Try version 4.0.2

**Comment by b4rtaz** [comment]
Thanks!
