### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by brandongoode** [dynamoose/dynamoose#2]
Use Q package to support both callback and promise logic.

**Comment by rkoberg** [comment]
Can we plug in any promises library similar to how mongoose does it?
```
import Promise from 'bluebird';
import mongoose from 'mongoose';
mongoose.Promise = Promise;
```

**Comment by davidhouweling** [comment]
Could we have an example of how to use this as a promise based library out of the box? Unless we are expected to use bluebird and promisifyAll the library (which is a bit annoying).

**Comment by brandongoode** [comment]
@davidhouweling - The main example uses the promise support.

https://github.com/automategreen/dynamoose#example

If you have a specific use case, I would be glad to help get it working for you.

**Comment by davidhouweling** [comment]
@brandongoode surpised i missed that, i guess it is because all the examples after that use callback approach. It would be nice if `.scan` and `.query` also supports it. I understand you have `.exec(callback)` but would be nice to just have it as `.exec().then(...)`.
