### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by fishcharlie** [dynamoose/dynamoose#788]
# TypeScript Support

## General

Dynamoose is committing to implementing TypeScript. This issue is to track the progress of that. It is important to note that this is converting the full project to TypeScript. It is not adding a manual type file that must be maintained separately.

The major reason this has not been done prior is due to my lack of experience with TypeScript. I have spent a bit of time recently learning TypeScript more, and feel like I'm confident enough to jump on board.

## Priorities

If it is determined that any one of these priorities can not be met, this project will be cancelled.

- Have an autogenerated type definition file packaged with Dynamoose so that users who use TypeScript with Dynamoose can get the autocomplete and type safety features of TypeScript
- Ensure no breaking changes for existing users of Dynamoose who are using vanilla JavaScript (as this will be part of a v2.1.0 release)

## Goals

- Figure out if there is a way when defining a Schema to have that supported in TypeScript,

## Release/Version Process

This will **likely** be part of a `v2.1` release. Alpha releases on NPM will take place alongside our existing `v2.0` beta. Especially with this new build process, I wouldn't be surprised if the alpha versions don't work on NPM. I will be testing it tho and doing my best to ensure everything works as well as possible.

## PR Process/Branch Strategy

Whenever a PR is made that will be merged into the `master` branch the same PR will need to be made to merge into the `alpha` branch. After you create a PR into the `master` branch, you can do one of the following:

- Create a second PR from your branch into `alpha`
- Manually make the changes you implemented in your PR on a separate branch and submit a PR for that into `alpha`

Due to the fact that lots of files will be renamed and modified heavily, for any code changes, it's extremely likely you will need to do the second option. For non code changes, you might be able to get away with the first option.

If you need any support in this feel free to tag me in a comment and I would be more than happy to help (or even do it for you).

**No PRs will be merged into `master` without a corresponding PR into `alpha` once that branch is created.**

## Next Steps

- [x] Create `alpha` branch
- [x] Set version to `v2.1.0-alpha.0` (922066f2969d0cb5463341ab260e32a9c3edc900)
- [x] Install TypeScript as developer dependency (5e8c2bfb9647e941b8d7f1de11754eabc0fc6617)
- [x] Create `tsconfig.json` file (2caf07e3c1de6879a74f84b3e59a274352d535f9)
- [x] Set the following options in `package.json` (3e13fae353967fcbd737bf04e05cfde5294edd22)
    - `main`: `dist/index.js`
    - `files`: `["dist"]`
    - `scripts`:
        - `build`: `tsc`
        - `build:watch`: `tsc -w`
        - `prepare`: `npm run build`
- [x] Add `dist` folder to ESLint ignore (f43a051566ac073803700dfd7400744324dccc9c)
- [x] Set version to `v2.1.0-alpha.1` (80b5e3e494dadadc5c18310cb9467dce359d5301)
- [x] Publish alpha release
- [x] Add `dist` folder to code coverage ignore (17150e979c444f9f0bb2a6b66aaa90482aac6f44)
- [x] Change all instances of `lib` to `dist` in `test` folder (a973abc0f2313ece7f14b17846c1c381174dc437)
- [x] Add all `.ts` files to ESLint ignore (2993835c09d6c8e73b184135f14b97444ce0bd9e)
- [x] Set version to `v2.1.0-alpha.3` (e0357386efab111cc671ed7dc876a921dd4c9896)
- [x] Publish alpha release
- [x] Start renaming `utils` `.js` files to `.ts`
- [x] Setup TypeScript in ESLint (https://www.wisdomgeek.com/development/web-development/how-to-setup-eslint-for-typescript-code/). Ensure that existing JS files are still covered by existing config, and new config is only for TS files. (8a5ba60f54bcf2e9e3fc69275b03df88a6d670b2)

## Future Steps

- [x] Set `declaration` TypeScript compilerOption to `true`
    - [ ] Set `"types": "dist/index.d.ts"` (or something like that) in `package.json`
- [ ] Set `strict` TypeScript compilerOption to `true`
- [ ] Need to figure out how to get code coverage working again

## Other Notes

- v2.1.0 will ONLY be a TypeScript release. No other features will be implemented between v2.0.x and v2.1.0. All further changes will take place in a v2.2.0 release which will start work immediately after v2.0.0 is released publicly.
- It's extremely unlikely that alpha versions will have release notes between versions
- Normally I make PRs and never commit to the `master` or any feature/major branch. This will **NOT** be the case for this project (especially during the alpha period). I will be committing directly to the `alpha` branch as work progresses. This also means any PRs you wish to submit to help are very appreciated, but should be communicated with me over Slack prior to doing the work to ensure there is no overlap. But I always appreciate PRs.
- It's very likely that once v2.0.0 is released publicly, v2.1.0 will enter a beta stage.
- TypeScript support/typings will be considered **beta** for v2.1.0. There is no guarantee that typings will be accurate, and we will be relying on support from the community to ensure accurate typings. If you notice a problem, submit a PR.

## Questions

- How can we best change our tests to support this? For now I think our temporary solution is to just change all the `test` files to point to `dist` instead of `lib`. This ensures that the compiled version works with our existing system and there is no breaking changes. But likely ruins code coverage, and doesn't seem like the best practice long term.
    - Maybe we have to consider moving to Jest?
- [x] When a user of Dynamoose sends me the stack trace, how can I translate that to TypeScript? Probably have to use the symbol maps or something, but gotta figure out how exactly to do that. (16af49c0dbcf7aa68fb7fe82c88ea32bedfb88a1)

## How can the community help?

1. Join the Slack channel. I might ask questions in there about TypeScript.
2. If you are interested in helping to contribute to this project, message me on Slack about next steps to ensure we are on the same page and I would **really appreciate any help**
3. Comment on this issue with any suggestions, feedback or improvements that you think can be made to TypeScript support
4. Test the `alpha` branch and let me know how it's working for you (good and bad)

**Comment by MickL** [comment]
Wow you did so much already! What about creating a PR draft so we could comment on the code directly?

**Comment by fishcharlie** [comment]
@MickL 

> Wow you did so much already!

Thanks!! Still **very** early. But I don't think it should be too much more difficult. I think the biggest things still to do are gonna be related to processes (ex. tests & source maps). I know you gave some thoughts around tests, but there are still some major concerns I have. Hopefully gonna talk to some other people to get some other perspectives on it as well. Removing tests/code related to type safety seems bad since only TypeScript enforces type safety. For JavaScript users this would cause some problems. Maybe down the road there is a solution to this, but for sure not in the scope of this work.

I think this should hopefully become more obvious the further we get in this project tho.

> What about creating a PR draft so we could comment on the code directly?

Sure, originally wasn't gonna do this since it's still so early. But I figured it's important to keep my eye on the merge status ability into master.

Check out #793

Comments and feedback now expected tho 🤣 

> Btw you said to join the Slack channel but thats not easy as it is invite only and you cant even request an invite on the Slack website.

In the README there is a badge at the top for "chat on slack". Most of the people joining the Slack channel come through that.

I did notice on the TypeScript repo, they have a link to a Discord channel as well on their "New Issue" page. Might try and see if I can do an external link to the Slack as well on that new issue page for us as well.

**Comment by fishcharlie** [comment]
The latest alpha version has support for TypeScript definitions. **Lots** of work still to be done in this area. There are things that are not optionals that should be, a lot of types are still type `any`. But I think this is ready to start being used in applications to test it out and start reporting feedback. Please leave comments here with any issues you run into when testing this alpha version.

Also, there is work being done to fix the types for `new Model()` to create a document. See #801 #802. Those are still work in progress PRs, and could change or break at anytime. Still a chance they will never be merged.
