### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by fishcharlie** [dynamoose/dynamoose#836]
The time has come... 🥁🥁🥁

# 🎉 VERSION 2.0 IS COMING 🎉

---

Ok but first. A bit of background. I've also tried to break it up with headers to make it a less intimidating read, but I'm hopeful that you will read everything since I believe there is a LOT of good information here.

## What is version 2.0?

Version 2.0 is a **total and complete** rewrite of Dynamoose. From the ground up. **TONS** of bug fixes, improvements, and more. I think in an early commit of v2, I deleted all the `lib` files, so it truly is a **total** rewrite.

## When did version 2.0 start? (Timeline)

The first commit to version 2.0 was made back on September 14th 2019 (over 7 months ago!!!). Since that time I have put a lot of work and effort into Dynamoose v2, probably more than I ever have before. Which is amazing and incredible.

## What are the positives of version 2.0?

I honestly believe Dynamoose is in a better position today than ever before. We have more tests than ever before, our code base is more DRY than ever before, and the foundation is stronger than ever before.

## What are some of the difficulties in this release?

Despite that, I foresee this release being potentially incredibly difficult. I think it's extremely difficult to do a full ground up rewrite of a project and not have it be a struggle in some aspect. There are a lot of breaking changes in Dynamoose v2. And probably a **lot** more that I'm unaware of. That has the potential to be a real struggle for a lot of users migrating to v2. I'm committed to helping users migrate to v2 tho. Feel free to reach out to me and I'll help as much as I can (you can find my contact information in so many different places, but I listed it at the bottom as well).

An even larger concern is what isn't in v2 yet. This includes (but is not limited to):

- Plugin Support
- TypeScript typings
- Populate

These are major features that I know a lot of users rely on. It is extremely difficult to ship a release without some of these key features.

## Why release now?

So, you might be asking then, why are you releasing v2.0 without these features? That is a completely fair and valid question. The reality is v2.0 has been in progress for 7 months. In that time I've largely abandoned focus on a lot of personal projects I've been working on. Sadly, I don't anticipate immediately going back to focus on those projects, as I see this being a pivotal moment in the life of Dynamoose. This is a point I view as the potential to truly take this project to the next level.

No software or project will ever truly be complete. At some point you have to throw your arms up, and release what you have. Every project grows and learns from that experience. I don't think there will ever be a point where I'm 100% confident with this release. It's a **large** release. But I believe we are at the point where despite some of these struggles, the best thing we can do is publish v2.0.

## What about version 2.1? (TypeScript support)

One of the struggles I mentioned above is TypeScript typings support. I have been hard at work refactoring Dynamoose to be refactored to be written in TypeScript. You can find that work on our `alpha` branches and versions. Version 2.1 will be released shortly after 2.0 (as you can see below). Keep in mind, TypeScript typings and support still have a **long** way to go. There are a lot of `any` types, and a lot of incorrect/confusing typings (especially related to optional properties with callbacks). So TypeScript Typings/Support in Version 2.1 will be considered **beta**. PRs would be amazing to help build that out and improve it (I know we had a bunch of support with the typings file in v1, which was amazing, I'm hopeful for that level of support here since I'm semi new to TypeScript).

### What does `beta` mean for TypeScript Typings/Support in Version 2.1?

Basically it means that you might find glitches in the typings TypeScript support. The NPM version won't be marked as beta. There might be some typings and autocomplete things when using TypeScript that are strange, or just down right wrong. This shouldn't limit your usage of v2.1 or discourage usage of it. If you have questions please [contact me](https://charlie.fish/contact).

And if you notice a problem, submit a pull request! Or an issue, but again, pull request would be **much** more helpful since I'm still new to TypeScript.

For JavaScript users nothing will change in v2.1.

## What about plugin support?

This is the next major thing I want to address after v2.1. I'm really looking for feedback here. So stay tuned for an issue asking for feedback and a proposal for plugin support in Dynamoose v2.x.

## What about `Model.populate`?

Again (same as plugin support), something that I want to address right after v2.1. Don't need as much feedback here since I have a vision of how I want this to work that I'm pretty happy with.

## What can I do to support Dynamoose?

Here are a few ideas of things you can do to support Dynamoose:

1. Submit a pull request with improvements (bug fixes, new features, TypeScript improvements)
2. Join the Slack channel (link in README badge) to ask questions or help others
3. Submit issues on GitHub with feature suggestions, bug reports, or anything else

## What can I do to support your work personally?

Ok so before I discuss this, I want to **stress** that this is not a requirement. I will continue to support Dynamoose as I have in the past (maybe not as much as I have recently, ie. spending the majority of my free time on it). Spending the majority of my free time on Dynamoose might have to change at some point, unless this program takes off. But I will continue to support Dynamoose. And Dynamoose isn't going anywhere. I also don't want this to come across as begging or asking for donations in a strong way. This is totally voluntary.

The main purpose and reason I have even considered this is due to the open source community moving towards more funding features (ie. GitHub Sponsors, and `npm fund`). As well as more importantly, some questions I've gotten recently about a tip jar or ways to support me. When I thought about how much time and work I spent on v2, it does make sense to provide this option to those who want to support my work here.

This is **likely** to change over time. For example, if Dynamoose gets more active contributors, I will likely add a separate option to support the project Dynamoose, instead of just me. More tiers and stuff might come over time as well, as well as potentially more methods.

[GitHub Sponsor (monthly)](https://github.com/sponsors/fishcharlie)
[PayPal.me (one time)](https://www.paypal.me/charliefish)

I also don't foresee this happening on an extreme level, but I do want to make it clear, the more support I get here, the more time I will dedicate to Dynamoose. I'm not sure exactly what that means yet, but I do want to make it clear that the more support I get here, the more time and effort I will dedicate to Dynamoose.

It is important to note that the links above are links to support me personally. Any donations will not necessarily go towards supporting Dynamoose directly, but will go towards supporting my involvement in Dynamoose. Dynamoose, after all, is the open source project I contribute most to (**by far**) 😉. In the event there is a lot of requests for supporting Dynamoose directly or depending on how well this goes, I will consider that as well (but that will likely take more planning and time to implement on my end, but totally open to that in the future potentially).

And if you do help support my involvement in Dynamoose ⭐️ **THANK YOU** 🎉.

---

Ok now the part everyone has been waiting for...

## Timeline

All dates below are in the year 2020. And keep in mind, I'm writing this on Friday April 24th. So everything written below is from that perspective (and will likely be outdated quickly).

### Short Term

| Date | Event |
| --- | --- |
| Friday April 24th | Merge final PRs (#831, #834) |
| Friday April 24th | Publish 2.0.0-beta.12 |
| Friday April 24th | Publish 2.1.0-alpha.9 |
| Monday April 27th | 🎉 Version 2.0.0 Release 🎉 |
| Monday April 27th | Merge `alpha` into `master` (#793) |
| Wednesday April 29th | 🎉 Version 2.1.0 Release 🎉 |

Between Friday - Wednesday the time I spend on Dynamoose, I plan on focusing exclusively on three things:

1. Answering questions and helping with migrations to v2 in Slack (link in README badge to join) and via my [contact methods](https://charlie.fish/contact)
2. TypeScript Typings Improvements (in preparation for v2.1.0)
3. Writing the changelog for v2.0

Also, during this period, I will be committing directly to `master`. Which is extremely rare for me. But TypeScript Typings Improvements is going to be an exception to this policy, just due to the goal of having a fast turn around time and being able to focus on improving the typings as opposed to managing pull requests.

### Long Term

After Wednesday my focus will shift to the following things:

1. Continuing to answer questions and helping with migrations to v2
2. Bug fixes
3. Plugin Support
4. `Model.populate` support

Then, it's likely (but not guaranteed) that I will take a break from anything major from Dynamoose, and focus a bit more on some personal projects that I want to work on. I'll still be active on Slack and able to fix bugs, answer questions and such.

After those things are complete, I foresee the exciting stuff really starting. The list of ideas I have for the future of Dynamoose is **insane**. I have a full page of notes of things I'd like to do to improve Dynamoose. I'm gonna keep a lot of that under wraps for a bit until I flesh it out a bit more, and decide how to prioritize things. But **WOW** I'm **excited** for the future ⭐.

Of course, everything in this long term section, is all up in the air at this point. It's all guesses and not finalized, and very likely could change. That being said, the 4 items I listed in the list are very likely to be the case tho (I **really** want to get plugin support and `Model.populate` support in).

---

Ok final few things.

- Dynamoose would not be where it is today without @brandongoode. 👏 to him for building Dynamoose. I couldn't be more grateful for his continued support even to this day. **THANK YOU** for everything @brandongoode.
- I'm always available to chat on Slack (link in README badge, Slack name is: Charlie Fish) or via any method on my [contact page](https://charlie.fish/contact).

**Comment by darksinge** [comment]
You kind of addressed this in the above post, but would you consider writing a migration guide from v1 to v2?

Also, I noticed the [docs](https://dynamoosejs.com/) have had a nice overhaul! However, are the old docs available anywhere? I'm not sure what the differences are between the version I'm currently using and the docs for the new 2.0 release.

**Comment by fishcharlie** [comment]
@darksinge Would totally consider a migration guide if you have things you’d like to see beyond the release notes! The release notes (specifically the breaking changes section) helped me a ton when migrating my projects. But I did have first hand knowledge of the code base. What else would you like to see?

Old documentation is available at https://v1.dynamoosejs.com

**Comment by darksinge** [comment]
@fishcharlie The release notes look like what I was looking for, thanks! 

It might be helpful for others if there was a link in the new docs to help with visibility. I wouldn't have known to look at the release notes if you hadn't mentioned it :)

**Comment by fishcharlie** [comment]
@darksinge Do you think in the FAQ section would be good enough here? There is currently a link in the footer to the changelog.

Just looking for feedback about where you would like to see it specifically.

Would love to see a PR if you are able to create one!!

**Comment by MickL** [comment]
I think you can unpin this? 😚

**Comment by fishcharlie** [comment]
@MickL Gonna leave it pinned until probably end of day tomorrow. Lots of good information here (some of which is still relevant, especially about future goals), so wanna give everyone a chance to read through it before unpinning it.
