### ISSUE TITLE
[FEATURE] Specify .query order (ScanIndexForward)

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#848]
A query result is ordered by the sortKey (rangeKey). DynamoDB gives the option to query it ascending or descending with [ScanIndexForward](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-ScanIndexForward) but Dynamoose does not have that option.

**Comment by IMBurbank** [comment]
@fishcharlie to clarify on the closure of #855, is this considered a feature that was in v1 but is not yet in v2?

I didn't find this in the pinned v2 issue #836 or in the breaking [changes notes](https://github.com/dynamoose/dynamoose/blob/master/CHANGELOG.md). I considered my issue a question about a method that changed (or was removed) across versions as opposed to a new feature request.

**Comment by fishcharlie** [comment]
@IMBurbank My bad. Yes this was an oversight on my part. v2 was in beta for a LONG time, and I never realized this until #855. So it should have been in #836 or breaking changelog. But I just didn't realize until now.

This will hopefully be fixed soon.

**Comment by IMBurbank** [comment]
@fishcharlie thanks for the clarification!
