### ISSUE TITLE
[FEATURE] Test connection

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#869]
It would be nice to have a function that tests if the connection is working.

Usecase: On bootup of my app I want to test if connection to DynamoDB is possible (e.g. tokens are set correct). Currently I have to make something like `.query` to do so.

**Comment by fishcharlie** [comment]
@MickL How would you like to see this done? `aws-sdk` doesn't really provide a method for testing the connection as far as I'm aware, so I'm not really sure how this would be implemented.

Is there a reason you can't just handle the error that comes back from `.query`? That would be more efficient than doing multiple requests. So would love to hear more about your use case around this.

**Comment by MickL** [comment]
Maybe it could do something simple like `GetItem` which should not result in a connection refused or unauthorized error.

**Comment by fishcharlie** [comment]
@MickL This is a great idea. But I have hesitations around this.

Mainly, this isn't something that is supported natively by AWS-SDK. If it was, I'd **totally** implement this. I think it's a great idea. But doing a `GetItem`, you need to pass in a table name, key, etc. And it would also increase cost. You could argue that you could do a `DescribeTable` or something to test it, so it wouldn't incur costs. BUT my problem with that, is that if we were to implement this, it should be generic (ex. `dynamoose.aws.ddb.connection.check()` or something like that). And one of the points of this is being able to do it before creating any models/tables. But if we do `DescribeTable`, it'd require us to know a table name, which makes it harder to be generic, and makes it harder to do before initializing models/tables. Now you could argue that you could do a `ListTables` (I think that's what it's called). But that is currently not done anywhere in Dynamoose. And that is normally not an IAM role I give any of my applications personally. Should a specific application really be able to access all the tables on an entire account? Depends on use case of course, but I'd argue no for most use cases.

I'd love to be able to do this tho. But the real solution here is for AWS to implement a method to check connection and secrets, then Dynamoose can implement that. To me, that is the real solution. Everything else, is weird band-aid workarounds that seem really weird. And those workarounds I'd argue have weird edge cases and problems of their own. I don't think the benefits are worth it enough to accept those weird problems they bring along.

But believe me, I've run into this problem before. But this is also mainly a developer feature. So luckily in production this doesn't really effect your workflow (or shouldn't in most cases).

Feel free to contact AWS or write on their community forms to request this feature tho!
