### ISSUE TITLE
[FEATURE] Using `Model.getItem()` return only specific attributes (ProjectionExpression)

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#881]
In DynamoDB there is `ProjectionExpression` (formerly `AttributesToGet`). I couldnt find this in the Dynamoose docs. For .query there is .attributes([]) but not for .getItem()?

Reference: https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html

P.S. Could you please add to the docs which request parameter [query.attributes(attributes)](https://dynamoosejs.com/guide/Query#queryattributesattributes) is using? `AttributesToGet` or `ProjectionExpression` or a custom solution? If I read the docs I want to be sure "Oh yes this function is using `ProjectionExpression`, thats exactly what I was looking for!", but currently I have to try it out and use the Dynamoose.logger to verify. The same may go for other functions.

**Comment by fishcharlie** [comment]
Oversight on my part. My bad. We also need to ensure this is done for other methods tho (ex. `batchGet` as well, and MAYBE transactions??).

**Comment by fishcharlie** [comment]
@MickL Just realizing now that `AttributesToGet` is a legacy parameter. We were originally using that to do this. Here is a pull request to migrate to `ProjectionExpression`: #886.

As for documentation. This is where I struggle time. Ideally, we'd have API documentation, and guides (like we do now). The details (such as the fact that we use `ProjectionExpression` would be housed in the API documentation. For now, I'll add it to the documentation, but ideally we should separate it out at some point.

Adding this to `Model.get` will be coming soon in a separate pull request.

**Comment by fishcharlie** [comment]
@MickL Model.get attributes pull request is up at #887
