### ISSUE TITLE
[BUG] Schema option `saveUnknown` is not working for an array

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#897]
### Summary:
Setting the Schema option `saveUnknown` to `true` works as expected, but using an array does save empty objects into DynamoDB:

```
           const catSchema = new dynamoose.Schema({
                name:          String,
                something:     Object,
                somethingElse: Object,
            }, {
                saveUnknown: [
                    'something',
                    'somethingElse',
                ],
            });
            const catModel       = dynamoose.model('Cat', catSchema);

            const cat = {
                name:          'Test',
                something:     {
                    hello: 'world',
                },
                somethingElse: {
                    hello:   {
                        world: 'hello!',
                    },
                    anArray: [1, 2, 3, 4],
                }
            };

            await catModel.create(cat);
```

```
aws:dynamodb:putItem:request - {
    "Item": {
        "name": {
            "S": "Test"
        },
        "something": {
            "M": {}
        },
        "somethingElse": {
            "M": {}
        }
    },
    "TableName": "Cat",
    "ConditionExpression": "attribute_not_exists(#__hash_key)",
    "ExpressionAttributeNames": {
        "#__hash_key": "name"
    }
}
```

**Comment by MickL** [comment]
So the problem was that `saveUnknown` only effects the first layer. In my case wildcards `*` and `**` should have been used as [stated in the docs](https://dynamoosejs.com/guide/Schema#new-dynamooseschemaschema-options).

**Comment by chadlittle** [comment]
Whats a valid example with **? I can't find any in the docs and can't save data here either.

**Comment by fishcharlie** [comment]
@chadlittle Something like the following:

```js
const schema = new dynamoose.Schema({"id": String}, {"saveUnknown": ["friend.**"]});
const User = dynamoose.model("User", schema);

await User.create({
    "id": "id1",
    "friend": {
        "age": 18,
        "name": {
            "first": "Charlie",
            "last": "Fish"
        }
    }
});
```

That example above will save the entire document to DynamoDB. Just as you see it written in `User.create`.

```js
const schema = new dynamoose.Schema({"id": String}, {"saveUnknown": ["friend.*"]});
const User = dynamoose.model("User", schema);

await User.create({
    "id": "id1",
    "friend": {
        "age": 18,
        "name": {
            "first": "Charlie",
            "last": "Fish"
        }
    }
});
```

The example above will save the document to DynamoDB as:

```json
{
    "id": "id1",
    "friend": {
        "age": 18,
        "name": {}
    }
}
```

Because it only matches properties one level deep.

- `**` - infinite level deep wildcard
- `*` - single level deep wildcard

**Comment by chadlittle** [comment]
Thanks, I've traced my issue down to whatever blob of object data I'm saving is messing with Dynamoose - its pretty nested. When I build out cases manually by hand, they save fine. I'll see if I can find a specific repo case.

**Comment by fishcharlie** [comment]
@chadlittle Sounds good. Keep in mind, it's also better to set the schema property as opposed to `saveUnknown`. That way it's more clear what is actually being saved. I'd only recommend saveUnknown for cases when you truly don't know what you are saving or what your schema looks like.
