### ISSUE TITLE
[BUG] dots in attribute names are not allowed

### ISSUE THREAD

**Issue by celalo** [dynamoose/dynamoose#907]
I admit it's not best practice but DynomoDB **allows** `.` (dot) in attribute names: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.NamingRules

However dynamoose **does NOT allow** it: https://github.com/dynamoose/dynamoose/blob/4345b21a43f3a3a2eedd6d8d0657da76000af38f/lib/Schema.ts#L319

**Comment by fishcharlie** [comment]
@celalo So the reasoning behind this is that Dynamoose does a lot of things where we split on `.` to determine nested attributes. This is used for things like properties within an Object or Array.

If you search for `.split(".")` in the code base you'll find a lot of instances of that.

If someone wants to make a pull request for this and has a clever idea for how to work around this, feel free. However for the time being this is pretty low priority, and I'm not even sure how we'd work around this while ensuring what we want to do works correctly.

**Comment by celalo** [comment]
Fair enough. I discovered this while working on an old table. I will consider recreating the table without dots in attribute names.

**Comment by fishcharlie** [comment]
@celalo If you have time and want to submit a proposal or pull request with specific ideas on how to address this that would be amazing. I'd love to support this. I just can't think of a way to do this without breaking things and making it clear to Dynamoose when something is a nested property vs just a property with `.`'s in it.

**Comment by celalo** [comment]
I am afraid I cannot find time to work on this at the moment. I can try to give it a try in the coming months.
