### ISSUE TITLE
[BUG] can't define a schema which includes a list of objects in typescript

### ISSUE THREAD

**Issue by julada** [dynamoose/dynamoose#909]
### Summary:
I cant define a schema which includes a list of objects.

### Code sample:
Working version with a javascript model:
```
 new dynamoose.Schema({
    id: {
      type: String,
      hashKey: true,
    },
    checks: {
      type: Array,
      schema: [{
          type: Object,
          schema: {
              type: String,
              status: String,
          },
      }],
    },
})
```
The type definitions blocks this schema because it needs a SchemaDefinition in the schema Attribute:
```
export const VerificationStateModel = model(
  process.env.VERIFICATION_STATE_TABLE_NAME,
  new Schema({
    id: {
      type: String,
      hashKey: true,
    },
    checks: {
      type: Array,
      schema: [{
          type: Object,
          schema: {
              type: String,
              status: String,
          },
      }],
    },
  })
);
```
If i dont mark the nested Object as Object type like this:
```
      schema: [{
         firstname: String,
         lastname: String,
      }],
```
 it leads to an runtime error

```
TypeMismatch: Expected accountHolderChecks.0 to be of type string, instead found type object.
      at checkTypeFunction (node_modules/dynamoose/lib/Document.ts:263:11)
      at node_modules/dynamoose/lib/Document.ts:270:7
          at Array.forEach (<anonymous>)
      at checkTypeFunction (node_modules/dynamoose/lib/Document.ts:268:11)
          at Array.map (<anonymous>)
      at Function.<anonymous> (node_modules/dynamoose/lib/Document.ts:282:111)
      at node_modules/dynamoose/dist/Document.js:8:71
      at __awaiter (node_modules/dynamoose/dist/Document.js:4:12)
```

I thought the problem is the attribute with name "type" but if i change the name, another error is thrown.... :

    TypeError: Cannot read property 'toLowerCase' of undefined
      at Schema.getAttributeTypeDetails (node_modules/dynamoose/lib/Schema.ts:485:21)
      at getValueTypeCheckResult (node_modules/dynamoose/lib/Document.ts:249:36)
      at checkTypeFunction (node_modules/dynamoose/lib/Document.ts:261:39)
      at node_modules/dynamoose/lib/Document.ts:270:7
          at Array.forEach (<anonymous>)

### Environment:

Operating System: macOS 
Operating System Version: Sierra
Node.js version (`node -v`): 13
NPM version: (`npm -v`):
Dynamoose version: 2.2.0

**Comment by fishcharlie** [comment]
@julada When does this error occur? On save? If so, can you show me what you are trying to save?

**Comment by julada** [comment]
Here is an minimal example which shows both errors:
https://github.com/julada/dynamoose-bug-example

**Comment by fishcharlie** [comment]
@julada Ahh. I **think** I see the problem. You have to define an array of objects. So the type of the schema object must be Object and you define the schema on that. This should also allow you to use `type` in your Schema. Which was the reason I chose to do it this way. Syntax is a bit more complex, but it's more explicit and helps Dynamoose detect the difference between a Dynamoose object with `type` and other settings, and the properties a user wants to define.

The example below was taken from the [`schema` documentation](https://dynamoosejs.com/guide/Schema#schema-object--array).

```js
{
    "friends": {
        "type": Array,
        "schema": [{
            "type": Object,
            "schema": {
                "zip": Number,
                "country": {
                    "type": String,
                    "required": true
                }
            }
        }]
    }
}
```

It looks like you might have done this in your original issue you wrote, but not in the code repo you sent me.

**Comment by julada** [comment]
Yes thats correct. So theres a problem with the type definitions?

**Comment by fishcharlie** [comment]
@julada Ohhh that code above produces a TypeScript error? Very likely. Could be the same as #854?? Wanna look at that issue and let me know if you think it's the same? Pull Requests to help with that would be much appreciated!

**Comment by GustavoEmmel** [comment]
I faced the same problem implementing dynamoose in my typescript code.

My workaround was as follows:

```
import { Schema as dynamooseSchema, model as dynamooseModel } from "dynamoose";

const myList = {
  listId: {
    type: String,
    required: false,
  }
};

const entity = new dynamooseSchema(
  {
    id: {
      type: String,
      required: true,
      hashKey: true,
    },
    someList: {
      type: Array,
      schema: [{
        type: Object,
        schema: myOffer as any,
      }],
    },
  },
  { timestamps: true }
);

export const schema = dynamooseModel(
  'myTable',
  entity
);

```

Some problems with the given solution:
 - I couldn't use the timestamps on myList
- I was unable to use the default attributes on myList
- Loading...
