### ISSUE TITLE
TS: Model.waitForActive.check should be optional

### ISSUE THREAD

**Issue by MickL** [dynamoose/dynamoose#911]
@fishcharlie wrote:

>    1. Add `export type DeepPartial<T> = {[P in keyof T]?: DeepPartial<T[P]>};` to `General.ts`
>    2. Change `export type ModelOptionsOptional = Partial<ModelOptions>;` to `export type ModelOptionsOptional = DeepPartial<ModelOptions>;`
>    3. Make `expires` non optional in `ModelOptions`, and fix errors that occur from this

**Comment by dnafication** [comment]
As per documentation: 

> Settings for how DynamoDB should handle waiting for the table to be active before enabling actions to be run on the table. This property can also be set to `false` to easily disable the behavior of waiting for the table to be active. For production environments we recommend setting this value to `false`.

But when you set the value to `false` ts complains

```
Type 'false' is not assignable to type 'ModelWaitForActiveSettings | undefined'.ts(2322)
```

I think its something we can solve in this ticket.
