### ISSUE TITLE
[FEATURE] Exporting types

### ISSUE THREAD

**Issue by ivan-ivory** [dynamoose/dynamoose#987]
### Summary:

It would be great if you export all types. I want to use my own shared interfaces in schemas, but I can't without importing `SchemaDefinition`

#### Schema
```
const schema: SchemaDefinition<IUserModel> = {}
```

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this feature has not already been suggested before
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@ivan-ivory Are you talking about something like #983?

**Comment by ivan-ivory** [comment]
> @ivan-ivory Are you talking about something like #983?

Yes, I'm also talking about Strong typed models. Only the `SchemaDefinition`interface is sufficient for my needs. You are already exporting it from `Schema.ts`, but you need to export it again from `index.ts` `declare const _default: { SchemaDefinition: typeof SchemaDefinition }`
